# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansb',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ansb',
            name='title',
        ),
        migrations.AddField(
            model_name='ansb',
            name='ver',
            field=models.CharField(default=True, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ansb',
            name='IP',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ansb',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
