# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0004_auto_20170807_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansbe',
            name='Inst',
        ),
        migrations.AddField(
            model_name='ansbe',
            name='Instance',
            field=models.CharField(choices=[('Server1', 'Server1'), ('Server2', 'Server2')], default='Server1', max_length=6),
        ),
        migrations.AlterField(
            model_name='ansb',
            name='Image',
            field=models.CharField(choices=[('Redhat', 'Redhat'), ('Centos', 'Centos'), ('Ubuntu', 'Ubuntu')], default='Centos', max_length=6),
        ),
        migrations.AlterField(
            model_name='ansb',
            name='Instance_Type',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=6),
        ),
        migrations.AlterField(
            model_name='ansb',
            name='key_name',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=7),
        ),
        migrations.AlterField(
            model_name='ansbe',
            name='OS',
            field=models.CharField(choices=[('Ubuntu', 'Ubuntu'), ('Centos', 'Centos'), ('Redhat', 'Redhat')], default='Centos', max_length=6),
        ),
    ]
