# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0005_auto_20170807_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansbe',
            old_name='Instance',
            new_name='Inst',
        ),
    ]
