# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0007_auto_20170807_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansbe',
            name='Instance',
            field=models.CharField(choices=[('Server1', 'Server1'), ('Server2', 'Server2')], default='Server1', max_length=7),
        ),
        migrations.AlterField(
            model_name='ansbe',
            name='Roles',
            field=models.CharField(choices=[('Apache', 'Apache'), ('Nginx', 'Nginx'), ('Java', 'Java'), ('Tomcat', 'Tomcat'), ('Common', 'Common')], default='Java', max_length=7),
        ),
    ]
