---

- name: Install fundamental packages
  hosts: servers
  become: yes
  roles:
    - common


- name: Install apache
  hosts: servers
  become: yes
  roles:
    - apache

- name: Install nginx
  hosts: servers
  become: yes
  roles:
    - nginx